import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#050505',
  },
  permissionText: {
    color: 'white',
    textAlign: 'center',
    marginTop: 100,
  },
  mainLayout: {
    flex: 1,
    flexDirection: 'row',
  },
  backButton: {
    position: 'absolute',
    top: 20,
    left: 40,
    zIndex: 10,
  },
  backButtonText: {
    color: '#ff4444',
    fontFamily: 'Courier',
    fontWeight: 'bold',
    fontSize: 16,
  },
  dashboard: {
    flex: 1.2,
    paddingLeft: 40,
    justifyContent: 'center',
  },
  systemText: {
    color: '#00ff00',
    fontFamily: 'Courier',
    fontSize: 14,
    marginBottom: 20,
    letterSpacing: 1,
  },
  instruments: {
    gap: 15,
  },
  row: {
    flexDirection: 'row',
    gap: 30,
  },
  controlsRow: {
    flexDirection: 'row',
    gap: 30,
    marginTop: 10,
  },
  label: {
    color: '#666',
    fontFamily: 'Courier',
    fontSize: 12,
    marginBottom: 5,
  },
  valueHighlight: {
    color: '#fff',
    fontFamily: 'Courier',
    fontSize: 18,
    fontWeight: 'bold',
  },
  valueText: {
    color: '#fff',
    fontFamily: 'Courier',
    fontSize: 16,
    width: 45,
    textAlign: 'center',
  },
  dashboardBtn: {
    borderWidth: 1,
    borderColor: '#444',
    paddingVertical: 5,
    paddingHorizontal: 15,
    borderRadius: 4,
    alignSelf: 'flex-start',
  },
  btnText: {
    color: '#ccc',
    fontFamily: 'Courier',
    fontWeight: 'bold',
  },
  zoomControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  cameraRig: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingRight: 40,
  },
  previewContainer: {
    width: 240,
    height: 180,
    borderWidth: 2,
    borderColor: '#333',
    borderRightWidth: 0,
    backgroundColor: '#000',
    overflow: 'hidden',
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
  },
  camera: {
    flex: 1,
  },
  crosshairVertical: {
    position: 'absolute',
    left: '50%',
    width: 1,
    height: '100%',
    backgroundColor: 'rgba(255,255,255,0.4)',
  },
  crosshairHorizontal: {
    position: 'absolute',
    top: '50%',
    width: '100%',
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.4)',
  },
  recDot: {
    position: 'absolute',
    top: 8,
    left: 8,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'red',
  },
  grip: {
    width: 80,
    height: 180,
    backgroundColor: '#1a1a1a',
    borderWidth: 2,
    borderColor: '#333',
    borderTopRightRadius: 12,
    borderBottomRightRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: -2, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 5,
  },
  shutterButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#333',
    borderWidth: 2,
    borderColor: '#111',
    justifyContent: 'center',
    alignItems: 'center',
  },
  shutterInner: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#ff4444',
  },
});
