import { Platform, StyleSheet } from 'react-native';

const scale = Platform.OS === 'android' ? 0.9 : 1;
const s = (value: number) => Math.round(value * scale);

export const styles = StyleSheet.create({
  darkroomRightPanel: {
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    backgroundColor: '#000',
  },
  // ★ 追加: 右パネル内で全画面を覆うコンテナ
  fullscreenContent: {
    ...StyleSheet.absoluteFillObject,
  },
  fullscreenImage: {
    ...StyleSheet.absoluteFillObject,
    resizeMode: 'cover',
  },
  fullscreenSkiaWrap: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 2,
    overflow: 'hidden',
  },
  emptyBackground: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#111',
  },
  // ... (残りのスタイルは変更なし) ...
  emptyBackgroundText: {
    color: '#333',
    fontSize: s(24),
    fontFamily: 'Courier',
    fontWeight: 'bold',
    letterSpacing: s(4),
  },
  resultModalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: s(16),
    zIndex: 100,
  },
  resultModalCard: {
    width: '88%',
    height: '70%',
    backgroundColor: '#040804',
    borderWidth: 1,
    borderColor: 'rgba(108, 174, 117, 0.35)',
    overflow: 'hidden',
  },
  resultHeader: {
    paddingTop: s(14),
    paddingHorizontal: s(14),
    paddingBottom: s(10),
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(108, 174, 117, 0.2)',
  },
  resultHeaderText: {
    color: '#6cae75',
    fontSize: s(18),
    letterSpacing: s(2),
    fontFamily: 'CourierPrime_700Bold',
    fontWeight: 'normal',
  },
  resultComparisonRow: {
    flex: 1,
    padding: s(14),
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(8),
  },
  resultColumn: {
    flex: 1,
    alignSelf: 'stretch',
    alignItems: 'center',
  },
  resultColumnTitle: {
    color: '#88c58f',
    fontSize: s(11),
    letterSpacing: s(1),
    fontFamily: 'CourierPrime_700Bold',
    fontWeight: 'normal',
    marginBottom: s(6),
  },
  resultArrowWrap: {
    width: s(24),
    justifyContent: 'center',
    alignItems: 'center',
  },
  resultArrowText: {
    color: '#6cae75',
    fontSize: s(22),
    fontFamily: 'CourierPrime_700Bold',
    fontWeight: 'normal',
  },
  resultImageFrame: {
    width: '100%',
    maxHeight: '92%',
    backgroundColor: '#000',
    borderWidth: 1,
    borderColor: 'rgba(108, 174, 117, 0.2)',
    overflow: 'hidden',
  },
  resultImage: {
    ...StyleSheet.absoluteFillObject,
    resizeMode: 'cover',
  },
  resultImageOverlay: {
    ...StyleSheet.absoluteFillObject,
    resizeMode: 'cover',
  },
  resultFooter: {
    paddingHorizontal: s(14),
    paddingBottom: s(12),
    paddingTop: s(2),
    alignItems: 'flex-end',
  },
  resultCloseButton: {
    borderWidth: 1,
    borderColor: 'rgba(108, 174, 117, 0.4)',
    paddingHorizontal: s(14),
    paddingVertical: s(6),
    backgroundColor: 'rgba(5, 24, 10, 0.6)',
  },
  resultCloseButtonText: {
    color: '#6cae75',
    fontFamily: 'CourierPrime_700Bold',
    letterSpacing: s(1),
    fontSize: s(12),
    fontWeight: 'normal',
  },
  overlayCenter: {
    backgroundColor: 'rgba(5, 5, 5, 0.7)',
    paddingVertical: s(30),
    paddingHorizontal: s(20),
    borderRadius: s(16),
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
    zIndex: 10,
    width: '85%',
  },
  timerLabel: {
    color: '#8B0000',
    fontSize: s(14),
    letterSpacing: s(3),
    marginBottom: s(8),
    fontWeight: '600',
    fontFamily: 'Courier',
  },
  timerText: {
    color: '#D41414',
    fontSize: s(54),
    fontWeight: '900',
    letterSpacing: s(2),
    fontFamily: 'monospace',
    textShadowColor: 'rgba(200, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: s(15),
    textAlign: 'center',
    width: '100%',
  },
  processingText: {
    marginTop: s(16),
    color: '#C5B7B7',
    fontSize: s(14),
    letterSpacing: s(1),
    fontFamily: 'Courier',
  },
  loadingWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: s(14),
    backgroundColor: '#050505',
  },
  loadingText: {
    color: '#E8D3D3',
    fontSize: s(14),
    fontWeight: '600',
    letterSpacing: s(1),
  },
  statusValue: {
    color: '#fff',
    fontSize: s(16),
    fontFamily: 'Courier',
    fontWeight: 'bold',
    marginBottom: s(24),
  },
  infoValue: {
    color: '#ccc',
    fontSize: s(14),
    fontFamily: 'Courier',
  },
  actionBtnText: {
    color: '#ccc',
    fontFamily: 'Courier',
    fontWeight: 'bold',
    fontSize: s(13),
  }
});