import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#050505',
  },
  mainContent: {
    flex: 1,
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 18,
  },
  glowLarge: {
    position: 'absolute',
    width: 560,
    height: 560,
    borderRadius: 280,
    backgroundColor: 'rgba(139, 0, 0, 0.16)',
    top: -140,
    right: -180,
  },
  glowSmall: {
    position: 'absolute',
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: 'rgba(139, 0, 0, 0.12)',
    bottom: -90,
    left: -90,
  },
  backButton: {
    position: 'absolute',
    top: 20,
    left: 8,
    padding: 10,
    zIndex: 30,
    elevation: 30,
  },
  backButtonText: {
    fontSize: 16,
    color: '#007AFF',
    fontWeight: '600',
  },
  pendingWrap: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 42,
  },
  slotsWrap: {
    width: '100%',
    alignItems: 'center',
    marginTop: 42,
    flex: 1,
  },
  slotsScroll: {
    width: '100%',
    flexGrow: 0,
  },
  slotsScrollContent: {
    paddingHorizontal: 20,
    alignItems: 'center',
    paddingVertical: 8,
  },
  slotCard: {
    width: 200,
    height: 300,
    alignItems: 'center',
    marginRight: 15,
  },
  slotImageWrap: {
    width: '100%',
    height: 260,
    borderRadius: 12,
    overflow: 'hidden',
    position: 'relative',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    backgroundColor: '#101010',
    shadowColor: '#000',
    shadowOpacity: 0.35,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  slotImage: {
    width: '100%',
    height: '100%',
  },
  slotBlur: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 2,
  },
  slotStatus: {
    marginTop: 10,
    color: '#D6CACA',
    fontSize: 13,
    fontWeight: '600',
  },
  emptySlot: {
    width: '100%',
    height: 260,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: 'rgba(255,255,255,0.25)',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.04)',
  },
  emptySlotTitle: {
    color: '#C5B7B7',
    fontSize: 16,
    fontWeight: '700',
  },
  emptySlotSub: {
    marginTop: 4,
    color: '#8E7E7E',
    fontSize: 11,
  },
  pendingTitle: {
    color: '#E8D3D3',
    fontSize: 16,
    marginBottom: 14,
    fontWeight: '700',
  },
  timerWrap: {
    alignItems: 'center',
    paddingBottom: 30,
    width: '100%',
  },
  timerLabel: {
    color: '#8B0000',
    fontSize: 13,
    letterSpacing: 3,
    marginBottom: 14,
    fontWeight: '600',
  },
  timerText: {
    color: '#D41414',
    fontSize: 64,
    fontWeight: '900',
    letterSpacing: 2,
    fontFamily: 'monospace',
    textShadowColor: 'rgba(255, 255, 255, 0.6)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 12,
  },
  processingText: {
    marginTop: 12,
    color: '#C5B7B7',
    fontSize: 13,
    letterSpacing: 0.5,
    textAlign: 'center',
    paddingHorizontal: 24,
  },
  loadingWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
  },
  loadingText: {
    color: '#E8D3D3',
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 1,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#1a1a1a',
    padding: 20,
    borderRadius: 12,
    alignItems: 'center',
    width: '80%',
  },
  modalTitle: {
    color: '#fff',
    fontSize: 18,
    marginBottom: 12,
    fontWeight: '700',
  },
  saveButton: {
    backgroundColor: '#8B0000',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
    marginBottom: 12,
  },
  saveButtonText: {
    color: '#fff',
    fontWeight: '700',
  },
  closeButton: {
    paddingVertical: 8,
    paddingHorizontal: 20,
  },
  closeButtonText: {
    color: '#ccc',
  },
  exitConfirmMessage: {
    color: '#E8D3D3',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 20,
  },
  exitConfirmDangerButton: {
    marginBottom: 10,
  },
});
