import { Platform, StyleSheet } from 'react-native';

const scale = Platform.OS === 'android' ? 0.9 : 1;
const edgeInset = Platform.OS === 'android' ? 6 : 0;
const s = (value: number) => Math.round(value * scale);

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  containerLight: {
    backgroundColor: '#FFFFFF',
  },
  containerDark: {
    backgroundColor: '#000000',
  },
  topBar: {
    height: s(96),
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingHorizontal: Platform.OS === 'android' ? s(24) : s(20),
  },
  coinBadge: {},
  coinBadgeText: {},
  filmBadgeRow: {
    marginTop: s(36),
    flexDirection: 'row',
    gap: s(8),
  },
  filmBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(6),
    paddingHorizontal: s(10),
    paddingVertical: s(6),
    borderWidth: 1,
    borderColor: '#D6D6D6',
    borderRadius: s(10),
    backgroundColor: '#FFFFFF',
  },
  filmBadgeDark: {
    backgroundColor: '#171717',
    borderColor: '#3A3A3A',
  },
  filmBadgeImage: {
    width: s(20),
    height: s(20),
    resizeMode: 'contain',
  },
  filmBadgeText: {
    fontSize: s(14),
    color: '#1A1A1A',
    fontWeight: '600',
  },
  menuButton: {
    width: s(40),
    height: s(40),
    marginTop: s(33),
    borderRadius: s(20),
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuButtonText: {
    fontSize: s(24),
    color: '#1B1B1B',
  },
  titleArea: {
    marginTop: s(40),
    alignItems: 'center',
  },
  title: {
    fontSize: s(22),
    letterSpacing: s(2),
    color: '#222222',
    fontWeight: '600',
    marginBottom: s(16),
  },
  checkButton: {
    borderWidth: 1,
    borderColor: '#2EA44F',
    paddingVertical: s(10),
    paddingHorizontal: s(18),
    borderRadius: s(22),
    backgroundColor: '#2EA44F',
    alignItems: 'center',
  },
  commitArea: {
    marginTop: s(22),
    alignItems: 'center',
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: s(14),
    fontWeight: '600',
  },
  infoText: {
    marginTop: s(10),
    fontSize: s(12),
    color: '#777777',
  },
  homeTextDark: {
    color: '#F1F1F1',
  },
  homeSubTextDark: {
    color: '#C7C7C7',
  },
  filmSelectorWrap: {
    marginTop: s(28),
    paddingHorizontal: Platform.OS === 'android' ? s(24) : s(20),
  },
  filmSelectorTitle: {
    fontSize: s(13),
    color: '#3C3C3C',
    marginBottom: s(10),
    fontWeight: '600',
  },
  filmSelectorRow: {
    paddingRight: s(20),
    gap: s(10),
  },
  filmChip: {
    minWidth: 148,
    borderWidth: 1,
    borderColor: '#DADADA',
    borderRadius: s(12),
    paddingVertical: s(10),
    paddingHorizontal: s(12),
    backgroundColor: '#FFFFFF',
  },
  filmChipSelected: {
    borderColor: '#222222',
    backgroundColor: '#F3F3F3',
  },
  filmChipTitle: {
    color: '#222222',
    fontSize: s(14),
    fontWeight: '700',
    marginBottom: s(2),
  },
  filmChipTitleSelected: {
    color: '#111111',
  },
  filmChipDesc: {
    color: '#666666',
    fontSize: s(12),
  },
  filmChipDescSelected: {
    color: '#3E3E3E',
  },
  bottomControls: {
    position: 'absolute',
    left: s(20) + edgeInset,
    right: s(20) + edgeInset,
    bottom: s(52) + edgeInset,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  sideControlLeft: {
    flex: 1,
    alignItems: 'flex-start',
  },
  sideControlRight: {
    flex: 1,
    alignItems: 'flex-end',
  },
  albumButton: {
    width: s(82),
    height: s(56),
    borderRadius: s(12),
    borderWidth: 1,
    borderColor: '#D2D2D2',
    backgroundColor: '#F5F5F5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  albumButtonDark: {
    backgroundColor: '#171717',
    borderColor: '#3A3A3A',
  },
  albumIcon: {
    fontSize: s(16),
    marginBottom: s(2),
  },
  albumLabel: {
    fontSize: s(11),
    color: '#4A4A4A',
    fontWeight: '700',
    letterSpacing: s(1.2),
  },
  shutterOuter: {
    width: s(78),
    height: s(78),
    borderRadius: s(39),
    borderWidth: 4,
    borderColor: '#E5E5E5',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  shutterOuterDark: {
    backgroundColor: '#101010',
    borderColor: '#2E2E2E',
  },
  shutterInner: {
    width: s(57),
    height: s(57),
    borderRadius: s(28.5),
    backgroundColor: '#F1F1F1',
    borderWidth: 1,
    borderColor: '#DDDDDD',
  },
  shutterInnerDark: {
    backgroundColor: '#202020',
    borderColor: '#3A3A3A',
  },
  darkroomButton: {
    width: s(82),
    height: s(56),
    borderRadius: s(12),
    borderWidth: 1,
    borderColor: '#6B0F0F',
    backgroundColor: '#0D0D0D',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: s(6),
  },
  darkroomIcon: {
    fontSize: s(16),
    marginBottom: s(2),
  },
  darkroomLabel: {
    fontSize: s(11),
    color: '#FF4A4A',
    fontWeight: '700',
  },
  rightEdgeGesture: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    width: s(24),
  },
  menuLayer: {
    ...StyleSheet.absoluteFillObject,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  menuBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.2)',
  },
  menuPanel: {
    height: '100%',
    paddingTop: s(32),
    paddingHorizontal: Platform.OS === 'android' ? s(24) : s(20),
    borderLeftWidth: 1,
    borderLeftColor: '#ECECEC',
    shadowColor: '#000000',
    shadowOpacity: 0.08,
    shadowRadius: s(10),
    shadowOffset: { width: -2, height: 0 },
    elevation: 4,
  },
  menuPanelLight: {
    backgroundColor: '#FFFFFF',
  },
  menuPanelDark: {
    backgroundColor: '#121212',
    borderLeftColor: '#2E2E2E',
  },
  menuHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: s(20),
  },
  menuTitle: {
    fontSize: s(16),
    fontWeight: '700',
    color: '#202020',
    letterSpacing: s(1),
  },
  closeText: {
    fontSize: s(26),
    color: '#202020',
  },
  aboutTitle: {
    fontSize: s(14),
    fontWeight: '700',
    color: '#2A2A2A',
    marginBottom: s(8),
  },
  aboutText: {
    fontSize: s(13),
    lineHeight: s(20),
    color: '#555555',
    marginBottom: s(24),
  },
  menuSectionTitle: {
    fontSize: s(13),
    fontWeight: '700',
    color: '#2A2A2A',
    marginBottom: s(8),
  },
  menuThemeRow: {
    flexDirection: 'row',
    gap: s(8),
    marginBottom: s(16),
  },
  menuThemeButton: {
    minWidth: 56,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#DADADA',
    borderRadius: s(10),
    paddingVertical: s(8),
    paddingHorizontal: s(10),
    backgroundColor: '#FFFFFF',
  },
  menuThemeButtonDark: {
    backgroundColor: '#1E1E1E',
    borderColor: '#3E3E3E',
  },
  menuThemeButtonActive: {
    borderColor: '#2EA44F',
  },
  menuThemeButtonText: {
    fontSize: s(13),
    color: '#1E1E1E',
    fontWeight: '600',
  },
  debugTitle: {
    fontSize: s(13),
    fontWeight: '700',
    color: '#2A2A2A',
    marginBottom: s(8),
  },
  debugAction: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#DADADA',
    borderRadius: s(10),
    paddingVertical: s(10),
    paddingHorizontal: s(12),
    marginBottom: s(8),
    backgroundColor: '#FFFFFF',
  },
  debugActionDark: {
    backgroundColor: '#1B1B1B',
    borderColor: '#3E3E3E',
  },
  debugActionText: {
    fontSize: s(13),
    color: '#1E1E1E',
    fontWeight: '600',
  },
  settingsAction: {
    width: '100%',
    minHeight: s(44),
    borderWidth: 1,
    borderColor: '#DADADA',
    paddingVertical: s(10),
    borderRadius: s(10),
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsActionDark: {
    borderColor: '#3E3E3E',
    backgroundColor: '#1A1A1A',
  },
  settingsActionText: {
    fontSize: s(14),
    color: '#1E1E1E',
    fontWeight: '600',
  },
  logoutAction: {
    marginTop: s(10),
    width: '100%',
    minHeight: s(44),
    borderWidth: 1,
    borderColor: '#E2B5B5',
    borderRadius: s(10),
    paddingVertical: s(10),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF7F7',
  },
  logoutActionText: {
    color: '#A12A2A',
    fontSize: s(14),
    fontWeight: '700',
  },
  menuTextDark: {
    color: '#F1F1F1',
  },
  menuSubTextDark: {
    color: '#C7C7C7',
  },
});
