import { Platform, StyleSheet } from 'react-native';

const scale = Platform.OS === 'android' ? 0.9 : 1;
const edgeInset = Platform.OS === 'android' ? 6 : 0;
const s = (value: number) => Math.round(value * scale);

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#050505',
  },
  backTouchable: {
    position: 'absolute',
    top: s(16) + edgeInset + (Platform.OS === 'android' ? s(6) : 0),
    left: s(12) + edgeInset,
    zIndex: 30,
    borderWidth: 1,
    borderColor: '#444',
    borderRadius: s(4),
    paddingHorizontal: s(10),
    paddingVertical: s(4),
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  backText: {
    fontSize: s(13),
    color: '#ff4444',
    fontWeight: 'bold',
    fontFamily: 'Courier',
    letterSpacing: 0.6,
  },

  mainLayout: {
    flex: 1,
    flexDirection: 'row',
  },
  scrollContent: {
    flexGrow: 1,
  },

  leftPanel: {
    flex: 0.42,
    flexDirection: 'row',
    alignItems: 'center',
  },
  gripDecor: {
    width: s(28),
    justifyContent: 'center',
    alignItems: 'center',
    gap: s(10),
    marginLeft: s(4),
  },
  navSquare: {
    width: s(8),
    height: s(8),
    borderWidth: 1,
    borderColor: '#555',
    backgroundColor: 'transparent',
  },
  navSquareActive: {
    backgroundColor: '#888',
    borderColor: '#888',
  },
  gripLine: {
    width: 1,
    height: s(10),
    backgroundColor: '#333',
  },
  dashboard: {
    flex: 1,
    alignSelf: 'stretch',
    paddingLeft: s(24),
    paddingTop: s(80),
    paddingRight: Platform.OS === 'android' ? s(8) : 0,
    justifyContent: 'flex-start',
  },
  systemText: {
    color: '#00ff00',
    fontFamily: 'Courier',
    fontSize: s(14),
    marginBottom: s(20),
    letterSpacing: 1,
  },
  systemTextdummy: {
    color: '#ffffff',
    fontFamily: 'Courier',
    fontSize: s(14),
    marginBottom: s(10),
    letterSpacing: 1,
  },
  statusBlock: {
    marginTop: Platform.OS === 'android' ? s(12) : 'auto',
    marginBottom: Platform.OS === 'android' ? s(6) : s(8),
  },
  instruments: {
    gap: s(14),
  },
  dashboardLabel: {
    color: '#666',
    fontFamily: 'Courier',
    fontSize: s(11),
    marginBottom: s(4),
  },
  dashboardValue: {
    color: '#ffffff',
    fontFamily: 'Courier',
    fontSize: s(16),
    fontWeight: 'bold',
  },

  rightPanel: {
    flex: 0.58,
    justifyContent: 'center',
    paddingHorizontal: Platform.OS === 'android' ? s(32) : s(28),
    paddingTop: s(26),
    paddingBottom: s(14) + (Platform.OS === 'android' ? edgeInset : 0),
  },
  sectionTitle: {
    fontSize: s(11),
    fontWeight: 'bold',
    fontFamily: 'Courier',
    color: '#00ff00',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: s(10),
  },
  formCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: '#0a0a0a',
    borderWidth: 1,
    borderColor: '#444',
    borderRadius: s(4),
    paddingHorizontal: s(12),
    paddingVertical: s(10),
    marginBottom: s(12),
  },
  formRow: {
    marginBottom: s(9),
  },
  formRowLast: {
    marginBottom: s(10),
  },
  label: {
    fontSize: s(10),
    fontWeight: 'bold',
    fontFamily: 'Courier',
    color: '#666',
    letterSpacing: 0.6,
    marginBottom: s(4),
  },
  input: {
    backgroundColor: '#0d0d0d',
    borderWidth: 1,
    borderColor: '#444',
    borderRadius: s(4),
    paddingVertical: s(5),
    paddingHorizontal: s(9),
    minHeight: s(30),
    fontSize: s(11),
    color: '#ffffff',
    fontFamily: 'Courier',
  },
  helperText: {
    fontSize: s(10),
    color: '#666',
    marginTop: s(3),
    fontFamily: 'Courier',
  },
  saveBtn: {
    borderWidth: 1,
    borderColor: '#444',
    backgroundColor: '#101010',
    borderRadius: s(4),
    paddingVertical: s(6),
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'flex-start',
    minWidth: s(108),
  },
  saveBtnText: {
    fontSize: s(11),
    fontWeight: 'bold',
    color: '#ffffff',
    fontFamily: 'Courier',
    letterSpacing: 0.8,
  },
  disabledBtn: {
    opacity: 0.6,
  },
  debugCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: '#0a0a0a',
    borderWidth: 1,
    borderColor: '#444',
    borderRadius: s(4),
    paddingHorizontal: s(12),
    paddingVertical: s(10),
  },
  debugCardLeft: {
    width: '100%',
    maxWidth: 300,
    backgroundColor: '#0a0a0a',
    borderWidth: 1,
    borderColor: '#444',
    borderRadius: s(4),
    paddingHorizontal: s(12),
    paddingVertical: s(10),
    marginTop: Platform.OS === 'android' ? s(4) : 0,
  },
  debugAllBtn: {
    marginBottom: s(8),
  },
  debugToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: s(6),
    borderWidth: 1,
    borderColor: '#2f2f2f',
    borderRadius: s(3),
    paddingHorizontal: s(6),
    paddingVertical: s(3),
    backgroundColor: '#0f0f0f',
  },
  debugToggleLabel: {
    fontSize: s(8),
    color: '#7fb37f',
    letterSpacing: 0.3,
  },
  debugToggleRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  debugToggleValue: {
    fontSize: s(8),
    color: '#cccccc',
    marginRight: s(3),
    letterSpacing: 0.3,
  },
  debugToggleSwitch: {
    transform: [{ scale: Platform.OS === 'android' ? 0.62 : 0.68 }],
  },
  debugButtonGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: s(6),
  },
  debugFilmBtn: {
    borderWidth: 1,
    borderColor: '#444',
    backgroundColor: '#101010',
    borderRadius: s(4),
    paddingVertical: s(5),
    paddingHorizontal: s(8),
  },
  debugFilmBtnText: {
    fontSize: s(10),
    color: '#ffffff',
    fontFamily: 'Courier',
    letterSpacing: 0.4,
  },
});
