import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#050505',
  },
  header: {
    height: 52,
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#1E4A1E',
    backgroundColor: '#0A0A0A',
  },
  backTouchable: {
    position: 'absolute',
    left: 12,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    paddingVertical: 0,
    paddingHorizontal: 8,
    zIndex: 20,
  },
  backText: {
    fontSize: 13,
    color: '#ff4444',
    fontWeight: '700',
    fontFamily: 'Courier',
    letterSpacing: 0.6,
  },
  headerTitle: {
    fontSize: 14,
    fontWeight: '700',
    fontFamily: 'Courier',
    color: '#00ff00',
    letterSpacing: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 14,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: '700',
    fontFamily: 'Courier',
    color: '#00ff00',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  sectionCard: {
    backgroundColor: '#0A0A0A',
    borderWidth: 1,
    borderColor: '#1E4A1E',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  inputRowLast: {
    marginBottom: 0,
  },
  label: {
    width: 120,
    fontSize: 11,
    fontWeight: '700',
    fontFamily: 'Courier',
    color: '#00ff00',
    letterSpacing: 0.6,
  },
  inputWrap: {
    flex: 1,
  },
  input: {
    backgroundColor: '#0F0F0F',
    borderWidth: 1,
    borderColor: '#2C5E2C',
    borderRadius: 4,
    paddingVertical: 6,
    paddingHorizontal: 10,
    minHeight: 34,
    fontSize: 12,
    color: '#E9FFE9',
    fontFamily: 'Courier',
  },
  helperText: {
    fontSize: 10,
    color: '#7ACB7A',
    marginTop: 4,
    fontFamily: 'Courier',
  },
  footer: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 12,
    borderTopWidth: 1,
    borderTopColor: '#1E4A1E',
    backgroundColor: '#0A0A0A',
  },
  footerBtn: {
    flex: 1,
    minHeight: 40,
    paddingVertical: 7,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  cancelBtn: {
    backgroundColor: '#120909',
    borderColor: '#5A1F1F',
  },
  cancelBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#ff4444',
    fontFamily: 'Courier',
    letterSpacing: 0.6,
  },
  saveBtn: {
    backgroundColor: '#0F1B0F',
    borderColor: '#00ff00',
  },
  saveBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#00ff00',
    fontFamily: 'Courier',
    letterSpacing: 0.7,
  },
  disabledBtn: {
    opacity: 0.6,
  },
});
