import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#050505',
  },
  backTouchable: {
    position: 'absolute',
    top: 16,
    left: 12,
    zIndex: 30,
    borderWidth: 1,
    borderColor: '#444',
    borderRadius: 4,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  backText: {
    fontSize: 13,
    color: '#ff4444',
    fontWeight: 'bold',
    fontFamily: 'Courier',
    letterSpacing: 0.6,
  },

  mainLayout: {
    flex: 1,
    flexDirection: 'row',
  },
  scrollContent: {
    flexGrow: 1,
  },

  leftPanel: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  gripDecor: {
    width: 28,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
    marginLeft: 4,
  },
  navSquare: {
    width: 8,
    height: 8,
    borderWidth: 1,
    borderColor: '#555',
    backgroundColor: 'transparent',
  },
  navSquareActive: {
    backgroundColor: '#888',
    borderColor: '#888',
  },
  gripLine: {
    width: 1,
    height: 10,
    backgroundColor: '#333',
  },
  dashboard: {
    flex: 1,
    alignSelf: 'stretch',
    paddingLeft: 24,
    paddingTop: 80,
    justifyContent: 'flex-start',
  },
  systemText: {
    color: '#00ff00',
    fontFamily: 'Courier',
    fontSize: 14,
    marginBottom: 18,
    letterSpacing: 1,
  },
  instruments: {
    gap: 14,
  },
  dashboardLabel: {
    color: '#666',
    fontFamily: 'Courier',
    fontSize: 11,
    marginBottom: 4,
  },
  dashboardValue: {
    color: '#ffffff',
    fontFamily: 'Courier',
    fontSize: 16,
    fontWeight: 'bold',
  },

  rightPanel: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 28,
    paddingTop: 38,
    paddingBottom: 20,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: 'bold',
    fontFamily: 'Courier',
    color: '#00ff00',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 10,
  },
  formCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: '#0a0a0a',
    borderWidth: 1,
    borderColor: '#444',
    borderRadius: 4,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 12,
  },
  formRow: {
    marginBottom: 9,
  },
  formRowLast: {
    marginBottom: 10,
  },
  label: {
    fontSize: 10,
    fontWeight: 'bold',
    fontFamily: 'Courier',
    color: '#666',
    letterSpacing: 0.6,
    marginBottom: 4,
  },
  input: {
    backgroundColor: '#0d0d0d',
    borderWidth: 1,
    borderColor: '#444',
    borderRadius: 4,
    paddingVertical: 5,
    paddingHorizontal: 9,
    minHeight: 30,
    fontSize: 11,
    color: '#ffffff',
    fontFamily: 'Courier',
  },
  helperText: {
    fontSize: 10,
    color: '#666',
    marginTop: 3,
    fontFamily: 'Courier',
  },
  saveBtn: {
    borderWidth: 1,
    borderColor: '#444',
    backgroundColor: '#101010',
    borderRadius: 4,
    paddingVertical: 6,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'flex-start',
    minWidth: 108,
  },
  saveBtnText: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#ffffff',
    fontFamily: 'Courier',
    letterSpacing: 0.8,
  },
  disabledBtn: {
    opacity: 0.6,
  },
  debugCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: '#0a0a0a',
    borderWidth: 1,
    borderColor: '#444',
    borderRadius: 4,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  debugCardLeft: {
    width: '100%',
    maxWidth: 300,
    backgroundColor: '#0a0a0a',
    borderWidth: 1,
    borderColor: '#444',
    borderRadius: 4,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  debugAllBtn: {
    marginBottom: 8,
  },
  debugButtonGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  debugFilmBtn: {
    borderWidth: 1,
    borderColor: '#444',
    backgroundColor: '#101010',
    borderRadius: 4,
    paddingVertical: 5,
    paddingHorizontal: 8,
  },
  debugFilmBtnText: {
    fontSize: 10,
    color: '#ffffff',
    fontFamily: 'Courier',
    letterSpacing: 0.4,
  },
});
